// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package order

import (
	flatbuffers "github.com/dolthub/flatbuffers/v23/go"

	Pizza "github.com/google/flatbuffers/tests/Pizza"
)

type FoodT struct {
	Pizza *Pizza.PizzaT `json:"pizza"`
	PizzaTest *Pizza.PizzaT `json:"pizza_test"`
}

func (t *FoodT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	pizzaOffset := t.Pizza.Pack(builder)
	pizzaTestOffset := t.PizzaTest.Pack(builder)
	FoodStart(builder)
	FoodAddPizza(builder, pizzaOffset)
	FoodAddPizzaTest(builder, pizzaTestOffset)
	return FoodEnd(builder)
}

func (rcv *Food) UnPackTo(t *FoodT) error {
	var err error
	Pizza, err := rcv.TryPizza(nil)
	if err != nil {
		return err
	}
	t.Pizza, err = Pizza.UnPack()
	if err != nil {
		return err
	}
	PizzaTest, err := rcv.TryPizzaTest(nil)
	if err != nil {
		return err
	}
	t.PizzaTest, err = PizzaTest.UnPack()
	if err != nil {
		return err
	}
	return err
}

func (rcv *Food) UnPack() (*FoodT, error) {
	if rcv == nil {
		return nil, nil
	}
	t := &FoodT{}
	err := rcv.UnPackTo(t)
	return t, err
}

type Food struct {
	_tab flatbuffers.Table
}

func InitFoodRoot(o *Food, buf []byte, offset flatbuffers.UOffsetT) error {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	return o.Init(buf, n+offset)
}

func TryGetRootAsFood(buf []byte, offset flatbuffers.UOffsetT) (*Food, error) {
	x := &Food{}
	return x, InitFoodRoot(x, buf, offset)
}

func TryGetSizePrefixedRootAsFood(buf []byte, offset flatbuffers.UOffsetT) (*Food, error) {
	x := &Food{}
	return x, InitFoodRoot(x, buf, offset+flatbuffers.SizeUint32)
}

func (rcv *Food) Init(buf []byte, i flatbuffers.UOffsetT) error {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
	if FoodNumFields < rcv.Table().NumFields() {
		return flatbuffers.ErrTableHasUnknownFields
	}
	return nil
}

func (rcv *Food) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Food) TryPizza(obj *Pizza.Pizza) (*Pizza.Pizza, error) {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Pizza.Pizza)
		}
		obj.Init(rcv._tab.Bytes, x)
		if Pizza.PizzaNumFields < obj.Table().NumFields() {
			return nil, flatbuffers.ErrTableHasUnknownFields
		}
		return obj, nil
	}
	return nil, nil
}

func (rcv *Food) TryPizzaTest(obj *Pizza.Pizza) (*Pizza.Pizza, error) {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Pizza.Pizza)
		}
		obj.Init(rcv._tab.Bytes, x)
		if Pizza.PizzaNumFields < obj.Table().NumFields() {
			return nil, flatbuffers.ErrTableHasUnknownFields
		}
		return obj, nil
	}
	return nil, nil
}

const FoodNumFields = 2

func FoodStart(builder *flatbuffers.Builder) {
	builder.StartObject(FoodNumFields)
}
func FoodAddPizza(builder *flatbuffers.Builder, pizza flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(pizza), 0)
}
func FoodAddPizzaTest(builder *flatbuffers.Builder, pizzaTest flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(pizzaTest), 0)
}
func FoodEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
