// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package models

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HelloReply struct {
	_tab flatbuffers.Table
}

func InitHelloReplyRoot(o *HelloReply, buf []byte, offset flatbuffers.UOffsetT) error {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	o.Init(buf, n+offset)
	if HelloReplyNumFields < o.Table().NumFields() {
		return flatbuffers.ErrTableHasUnknownFields
	}
	return nil
}

func TryGetRootAsHelloReply(buf []byte, offset flatbuffers.UOffsetT) (*HelloReply, error) {
	x := &HelloReply{}
	return x, InitHelloReplyRoot(x, buf, offset)
}

func GetRootAsHelloReply(buf []byte, offset flatbuffers.UOffsetT) *HelloReply {
	x := &HelloReply{}
	InitHelloReplyRoot(x, buf, offset)
	return x
}

func TryGetSizePrefixedRootAsHelloReply(buf []byte, offset flatbuffers.UOffsetT) (*HelloReply, error) {
	x := &HelloReply{}
	return x, InitHelloReplyRoot(x, buf, offset+flatbuffers.SizeUint32)
}

func GetSizePrefixedRootAsHelloReply(buf []byte, offset flatbuffers.UOffsetT) *HelloReply {
	x := &HelloReply{}
	InitHelloReplyRoot(x, buf, offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *HelloReply) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HelloReply) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HelloReply) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

const HelloReplyNumFields = 1

func HelloReplyStart(builder *flatbuffers.Builder) {
	builder.StartObject(HelloReplyNumFields)
}
func HelloReplyAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(message), 0)
}
func HelloReplyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
